### ISSUE TITLE
Feature Request - runExperience(experience-id)

### ISSUE THREAD

**Issue by sb-chericks** [convertcom/javascript-sdk#166]
I'd like it if the user context function `runExperience({experience-key})` could either be updated, overloaded, or an additional function added to support `runExperience({experience-id})`.

The key appears to be assigned at the experience creation, but cannot be renamed or changed from the admin portal as far as I can tell. I have renamed some experiences, and the key no longer lines up with the name of the experiment it identifies.

Additionally, I don't see any possible way to get the value of the key after creating an experience on the admin portal without actually running the experience at least once and checking the server payload.

Ideally I'd really like to support actions with experiences with the `long` id, which is how it seems that most other artifacts in the SDK are identified, and this value is publicly and clearly accessible on the admin portal.

**Comment by abbaseya** [comment]
@sb-chericks the experience `key` needs to be unique as per our [API specs](https://api.convert.com/doc/serving/#tag/Project-Config/operation/getProjectConfig).
At the moment, we do not force the key to be unique, but you can specify unique experience key upon creation, even if the experience name already exists on the same project. Think of the experience `key` as a unique ID, that's why it remains the same when you rename the experience (_just like the experience `id`_).

As of your requested feature to support `runExperience({experience-id})`, can you explain the benefit from doing so at your end? we designed the context methods to deal with `key` instead of `id` for convenience, yet your requests sounds like there's a problem you need to solve, we'd like to shed some light on that problem so that we can help producing a better implementation.

Last but not least, you can find the `key` of your existing experiences by showing the `Key` column at the experiences list.
<img width="842" alt="Screenshot 2024-06-10 at 7 11 25 PM" src="https://github.com/convertcom/javascript-sdk/assets/8595210/d539d75b-4482-4333-a2a9-e07717538559">
<img width="332" alt="Screenshot 2024-06-10 at 7 12 59 PM" src="https://github.com/convertcom/javascript-sdk/assets/8595210/8dbcdb44-f370-408b-8838-4db560a379d3">

**Comment by sb-chericks** [comment]
> @sb-chericks the experience key needs to be unique as per our [API specs](https://api.convert.com/doc/serving/#tag/Project-Config/operation/getProjectConfig).
> At the moment, we do not force the key to be unique, but you can specify unique experience key upon creation, even if the experience name already exists on the same project. Think of the experience key as a unique ID, that's why it remains the same when you rename the experience (just like the experience id).

I understand that its a unique identifier, I guess I just don't understand why you also have the same identifier `id` also on the entity. `Id` is a well-known, industry standard name for the primary identifier for an entity. You use `Id` when identifying the project, and account entities. I guess it just doesn't make sense why experience is different.

> As of your requested feature to support runExperience({experience-id}), can you explain the benefit from doing so at your end? we designed the context methods to deal with key instead of id for convenience, yet your requests sounds like there's a problem you need to solve, we'd like to shed some light on that problem so that we can help producing a better implementation.

The benefit is that I'm consistently using the same entity identifier of `Id` for all of the entities I'm transacting with. I also use the REST API you guys have, so its an additional obstacle to track both the `Id` and the `key` for separate purposes on the javascript SDK.

> Last but not least, you can find the key of your existing experiences by showing the Key column at the experiences list.

I wish this was the case for me, as it would solve most of my problems, however I don't have that option in my web portal. 
Here's the options I see available in the Experience browser.
![image](https://github.com/convertcom/javascript-sdk/assets/160796564/0fc83021-dc41-487a-bd59-461ba6fd07b8)

I have admin level permissions on all projects, so I hope its not a permissions issue?
![image](https://github.com/convertcom/javascript-sdk/assets/160796564/be9453bb-986c-4bf2-9cdf-bd153b644ce3)

Any ideas on what I can do to make that column option appear?

**Comment by abbaseya** [comment]
@sb-chericks I'm assuming that you have the `key` column in your UI by now, closing this for now. Feel free to re-open if that's not the case.

**Comment by sb-chericks** [comment]
> @sb-chericks I'm assuming that you have the `key` column in your UI by now, closing this for now. Feel free to re-open if that's not the case.

Negative, that column is still not available to me.

![image](https://github.com/user-attachments/assets/c5a62e2c-11c6-4ed2-af2d-25141335d349)

**Comment by abbaseya** [comment]
@sb-chericks this is a web project and not a full stack project, that's why you do not have the `key` column in there, that only works with full stack projects. In fact, this SDK is designed to work only with full stack projects. FYI.

**Comment by sb-chericks** [comment]
Ah, okay I see that now. I guess we can close this issue. It does appear that 'Full Stack' projects are in beta however. I'll try to lookup when these are migrated to general availability, and if its possible to convert my existing web project into one.
