### ISSUE TITLE
Segments from visitorProperties are not included in bucketing request

### ISSUE THREAD

**Issue by mattddean** [convertcom/javascript-sdk#59]
If I call `runExperience` for a customer whose data has not been stored in data-manager, the visitorProperties that I pass to `runExperience` will not make their way into the [bucketing request](https://github.com/convertcom/javascript-sdk/blob/c3b2883591463466a6fe9c9b6d099b54c3dcfe09/packages/data/src/data-manager.ts#L531C34-L531C34).

I think this is because [`segments` comes from the data store](https://github.com/convertcom/javascript-sdk/blob/c3b2883591463466a6fe9c9b6d099b54c3dcfe09/packages/data/src/data-manager.ts#L447), but the data store has not been influenced by the visitorProperties provided to the `runExperience` function.

What I'm trying to do:

```ts
userContext.runExperience('experience-key', { 
  visitorProperties: { 
    [SegmentsKeys.COUNTRY]: 'US' 
  }
})
```

**Comment by abbaseya** [comment]
@mattddean good to hear from you again, and happy new year 😉 
The visitorProperties you're passing meant for matching against audience rules associated with the experience. They're not passed down to the bucketing request.

I think what you're looking for is:
```typescript
// the following will update the data store
userContext.setDefaultSegments({ 
    [SegmentsKeys.COUNTRY]: 'US' 
});
// now you do not have to pass the above visitor properties when evaluating experience
userContext.runExperience('experience-key);
```

**Comment by abbaseya** [comment]
@mattddean in fact, your inquiry raises a very important aspect that we need to clarify in upcoming releases. The relation between `visitorProperties` and `segments`. Additionally, we agree with you on the part that `visitorProperties` should be updated in data store. Would it make more sense?

**Comment by abbaseya** [comment]
@mattddean are you saying that we should not update the data store with the passed argument `visitorProperties` when calling `runExperience` ? I thought that's what you expected to avoid the confusion there.
On the other hand, we only include a [subset](https://api.convert.com/doc/serving/#tag/Experiences-Tracking/operation/sendTrackingEvents) of the visitor segments with the API request, so that they show on Convert Reports. We might include more in the future, in case that's what you expect (_kindly confirm_).

That said, we use the term `visitorProperties` to represent the data to be matched for audiences rules. At the moment, we do not store those into data store.
The upcoming release shall extract the following key subset if present in your input `visitorProperties`:
`browser`, `devices`, `source`, `campaign`, `visitorType`, and `country`,
Only those will to be kept in data store (_overriding old values_). I will include detailed description explaining the difference between Audiences, Segments, and visitorProperties. I'll keep you posted.

**Comment by mattddean** [comment]
@abbaseya I think it would make more sense if runExperience did not mutate anything. It should just pass the passed data directly to the API request and not mutate the data store. Otherwise, you could have a weird situation where you remove one runExperience call and all of a sudden another runExperience call behaves differently.

**Comment by abbaseya** [comment]
@mattddean we've just release v2.1.0 which does the following:
1. Only reporting segments are synced with persistent store (_if provided_).
2. Input visitorProperties now merged with both in-memory and persistent upon bucketing experiences/features.
3. Earlier we were auto-update in-memory `visitorProperties` upon bucketing, now we do not, unless an explicit `updateVisitorProperties` option is passed to running experiences/features.

Additionally, there're 2 new context methods:
1. [Context.updateVisitorProperties](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#update-visitor-properties)
2. [Context.getConfigEntity](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#get-config-entity) - might be handy when you want to extract additional information from config based on keys received at the events callback (_[example](https://github.com/convertcom/javascript-sdk/tree/main/packages/js-sdk#events) GA implementation_)
